package dev.brella.kornea.blaseball.beans

import dev.brella.kornea.blaseball.GameID
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

@Serializable
data class BlaseballDatabaseLeague(
    val id: String,
    val subleagues: List<String>,
    val name: String,
    val tiebreakers: String
)

@Serializable
data class BlaseballDatabaseSubleague(
    val id: String,
    val divisions: List<String>,
    val name: String
)

@Serializable
data class BlaseballDatabaseDivision(
    val id: String,
    val teams: List<String>,
    val name: String
)

@Serializable
data class BlaseballDatabaseTeam(
    val id: String,
    val lineup: List<String>,
    val rotation: List<String>,
    val bullpen: List<String>,
    val bench: List<String>,
    val fullName: String,
    val location: String,
    val mainColor: String,
    val nickname: String,
    val secondaryColor: String,
    val shorthand: String,
    val emoji: String,
    val slogan: String,
    val shameRuns: Double,
    val totalShames: Int,
    val totalShamings: Int,
    val seasonShames: Int,
    val seasonShamings: Int,
    val championships: Int,
    val rotationSlot: Int,
    val weekAttr: List<String>,
    val gameAttr: List<String>,
    val seasAttr: List<String>,
    val permAttr: List<String>,
    val teamSpirit: Double,
    val card: Int,
    /*   */
    val tournamentWins: Int,
    val stadium: String?,
    val imPosition: Double,
    val eDensity: Double,
    val eVelocity: Double,
    val state: JsonObject,
    val evolution: Double,
    val winStreak: Double
)

@Serializable
data class BlaseballDatabasePlayer(
    val id: String,
    val anticapitalism: Double,
    val baseThirst: Double,
    val buoyancy: Double,
    val chasiness: Double,
    val coldness: Double,
    val continuation: Double,
    val divinity: Double,
    val groundFriction: Double,
    val indulgence: Double,
    val laserlikeness: Double,
    val martyrdom: Double,
    val moxie: Double,
    val musclitude: Double,
    val name: String,
    val bat: String,
    val omniscience: Double,
    val overpowerment: Double,
    val patheticism: Double,
    val ruthlessness: Double,
    val shakespearianism: Double,
    val suppression: Double,
    val tenaciousness: Double,
    val thwackability: Double,
    val tragicness: Double,
    val unthwackability: Double,
    val watchfulness: Double,
    val pressurization: Double,
    val totalFingers: Int,
    val soul: Int,
    val deceased: Boolean,
    val peanutAllergy: Boolean,
    val cinnamon: Double,
    val fate: Int,
    val armor: String,
    val ritual: String,
    val coffee: Int,
    val blood: Int,
    val permAttr: List<String>,
    val seasAttr: List<String>,
    val weekAttr: List<String>,
    val gameAttr: List<String>,
    val hitStreak: Int,
    val consecutiveHits: Int,
    val baserunningRating: Double,
    val pitchingRating: Double,
    val hittingRating: Double,
    val defenseRating: Double,
    val leagueTeamId: String?,
    val tournamentTeamId: String?,
    val eDensity: Double,
    val state: JsonObject,
    val evolution: Double
)

@Serializable
data class BlaseballDatabaseGame(
    val id: GameID,
    val basesOccupied: List<Int>,
    val baseRunners: List<String>,
    val baseRunnerNames: List<String>,
    val outcomes: List<String>,
    val terminology: String,
    val lastUpdate: String,
    val rules: String,
    val statsheet: String,
    val awayPitcher: String?,
    val awayPitcherName: String,
    val awayBatter: String?,
    val awayBatterName: String?,
    val awayTeam: String,
    val awayTeamName: String,
    val awayTeamNickname: String,
    val awayTeamColor: String,
    val awayTeamEmoji: String,
    val awayOdds: Double,
    val awayStrikes: Double,
    val awayScore: Double,
    val awayTeamBatterCount: Int,
    val homePitcher: String?,
    val homePitcherName: String,
    val homeBatter: String?,
    val homeBatterName: String?,
    val homeTeam: String,
    val homeTeamName: String,
    val homeTeamNickname: String,
    val homeTeamColor: String,
    val homeTeamEmoji: String,
    val homeOdds: Double,
    val homeStrikes: Double,
    val homeScore: Double,
    val homeTeamBatterCount: Int,
    val season: Int,
    val isPostseason: Boolean,
    val day: Int,
    val phase: Int,
    val gameComplete: Boolean,
    val finalized: Boolean,
    val gameStart: Boolean,
    val halfInningOuts: Double,
    val halfInningScore: Double,
    val inning: Double,
    val topOfInning: Boolean,
    val atBatBalls: Int,
    val atBatStrikes: Double,
    val seriesIndex: Int,
    val seriesLength: Int,
    val shame: Boolean,
    val weather: Int,
    val baserunnerCount: Int,
    val homeBases: Double,
    val awayBases: Double,
    val repeatCount: Int,
    val awayTeamSecondaryColor: String,
    val homeTeamSecondaryColor: String,
    val homeBalls: Int,
    val awayBalls: Int,
    val homeOuts: Int,
    val awayOuts: Int,
    val playCount: Int,
    val tournament: Int,
    val baseRunnerMods: List<String>,
    val homePitcherMod: String,
    val homeBatterMod: String,
    val awayPitcherMod: String,
    val awayBatterMod: String,
    val scoreUpdate: String,
    val scoreLedger: String,
    val stadiumId: JsonElement?,
    val secretBaserunner: JsonElement?,
    val topInningScore: Double,
    val bottomInningScore: Double,
    val newInningPhase: Int,
    val gameStartPhase: Int,
    val isTitleMatch: Boolean
)

@Serializable
data class BlaseballDatabasePlayoffs(
    val id: String,
    val name: String,
    val numberOfRounds: Int,
    val playoffDay: Int,
    val rounds: List<String>,
    val season: Int,
    val tomorrowRound: Int,
    val winner: String,
    val tournament: Int
)